#ifndef NOKIALCDCONFIG_H_
#define NOKIALCDCONFIG_H_

#define NOKIALCD_RST_BIT 4
#define NOKIALCD_SCE_BIT 3
#define NOKIALCD_DC_BIT 2
#define NOKIALCD_MOSI_BIT 1
#define NOKIALCD_SCLK_BIT 0

#endif /*NOKIALCDCONFIG_H_*/
