#ifndef NOKIALCDCONFIG_H_
#define NOKIALCDCONFIG_H_

#define NOKIALCD_RST_BIT 23
#define NOKIALCD_SCE_BIT 8
#define NOKIALCD_DC_BIT 24
#define NOKIALCD_MOSI_BIT 10
#define NOKIALCD_SCLK_BIT 11

#endif /*NOKIALCDCONFIG_H_*/
